name: Update Clash Config

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install pyyaml requests

      - name: 执行更新脚本
        run: python update.py

      - name: 提交更新
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sakuracat.yaml
          git commit -m "自动更新配置文件" || echo "No changes"
          git push
